[project]
name = "atari-deep-q-network"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium[atari]>=1.2.2",
    "numpy>=2.3.4",
    "torch>=2.9.0",
]
