training_config:
  nb_episodes: 5000
  nb_steps_per_episode: 10000
  memory_capacity: 100000
  batch_size: 32
  train_frequency: 4
  lr: 0.00025
  gamma: 0.99
  agent_epsilon_start: 1.0
  agent_epsilon_decay: 1000000
  agent_epsilon_end: 0.1
  target_update_frequency: 10000
  checkpoint_frequency: 500
  learning_starts: 10000
